schema_version = "1.0.0"

blender_version_min = "4.2.0"

id = "naythan_simple_retargeting_extension"
name = "simple retargeting extension"

version = "0.0.1"
tagline = "simple retargeting extension"
type = "add-on"
tags = ["Animation", "Rigging"]
platforms = ["windows-x64",  "windows-arm64", "macos-arm64", "macos-x64", "linux-x64",]

website = "https://github.com/NaythanTouqe/blender_retargeter.git"
license = [ "SPDX:GPL-3.0-or-later", ]
maintainer = "naythan_touqe"

[build]
paths_exclude_pattern = [
	"build/",
	"__pycache__/",
	".*",
	"*.zip",
]
